[package]
name = "rust"
version = "1.0.1"
authors = ["Zingolabs <zingo@zingolabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = { version = "0.10.2", default-features = false }
android_logger = "0.8.6"
log = "0.4.8"
rustlib = { path = "../lib" }

[lib]
crate-type = ["cdylib"]