[package]
name = "rust"
version = "1.0.1"
authors = ["Zingolabs <zingo@zingolabs.com>"]
edition = "2021"

[dependencies]
jni = { version = "0.19.0", default-features = false }
android_logger = "0.11"
log = { workspace = true }
rustlib = { path = "../lib" }

[dev-dependencies]
tokio =  { version = "1.24.2", features = ["full"] }
zingo-testutils = { git="https://github.com/Oscar-Pepper/zingolib", default-features=true, branch = "mobile_regtest_fix_sync_on_init" }
json = "0.12.4"
env_logger = "0.10.0"
test_utils = { path = "../test_utils" }

[lib]
crate-type = ["dylib"]

